import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useForm, useFieldArray } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { format } from 'date-fns';
import {
  ClipboardCheck,
  ArrowLeft,
  Plus,
  Trash2,
  Save,
  Calendar,
} from 'lucide-react';
import { AppLayout } from '@/components/layout/AppLayout';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
} from '@/components/ui/form';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Calendar as CalendarComponent } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { Separator } from '@/components/ui/separator';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/integrations/supabase/client';
import { cn } from '@/lib/utils';

interface Department {
  id: string;
  name: string;
}

const auditItemSchema = z.object({
  requirement: z.string().min(1, 'Requirement is required'),
  evidence_required: z.string().optional(),
});

const auditFormSchema = z.object({
  title: z.string().min(1, 'Title is required'),
  description: z.string().optional(),
  iso_clause: z.string().optional(),
  audit_date: z.date({ required_error: 'Audit date is required' }),
  department_id: z.string().optional(),
  items: z.array(auditItemSchema).min(1, 'At least one checklist item is required'),
});

type AuditFormData = z.infer<typeof auditFormSchema>;

export default function AuditCreate() {
  const navigate = useNavigate();
  const { toast } = useToast();
  const { profile } = useAuth();
  const [departments, setDepartments] = useState<Department[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const form = useForm<AuditFormData>({
    resolver: zodResolver(auditFormSchema),
    defaultValues: {
      title: '',
      description: '',
      iso_clause: '',
      items: [{ requirement: '', evidence_required: '' }],
    },
  });

  const { fields, append, remove } = useFieldArray({
    control: form.control,
    name: 'items',
  });

  useEffect(() => {
    async function fetchDepartments() {
      const { data } = await supabase.from('departments').select('id, name').order('name');
      if (data) setDepartments(data);
    }
    fetchDepartments();
  }, []);

  async function onSubmit(data: AuditFormData) {
    if (!profile) return;
    setIsSubmitting(true);

    try {
      // Create the audit checklist
      const { data: audit, error: auditError } = await supabase
        .from('audit_checklists')
        .insert({
          title: data.title,
          description: data.description || null,
          iso_clause: data.iso_clause || null,
          audit_date: format(data.audit_date, 'yyyy-MM-dd'),
          department_id: data.department_id || null,
          auditor_id: profile.id,
          tenant_id: profile.tenant_id,
          status: 'draft',
          checklist_number: '', // Will be auto-generated by trigger
        } as any)
        .select()
        .single();

      if (auditError) throw auditError;

      // Create the checklist items
      const items = data.items.map((item, index) => ({
        checklist_id: audit.id,
        tenant_id: profile.tenant_id,
        item_number: index + 1,
        requirement: item.requirement,
        evidence_required: item.evidence_required || null,
      }));

      const { error: itemsError } = await supabase
        .from('audit_checklist_items')
        .insert(items);

      if (itemsError) throw itemsError;

      toast({
        title: 'Audit Created',
        description: `Audit ${audit.checklist_number} has been created.`,
      });

      navigate(`/audits/${audit.id}`);
    } catch (error: any) {
      toast({
        variant: 'destructive',
        title: 'Error',
        description: error.message,
      });
    } finally {
      setIsSubmitting(false);
    }
  }

  return (
    <AppLayout>
      <div className="max-w-4xl mx-auto space-y-6">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" onClick={() => navigate('/audits')}>
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <div>
            <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
              <ClipboardCheck className="h-6 w-6 text-primary" />
              Create Internal Audit
            </h1>
            <p className="text-muted-foreground">
              Set up a new internal audit checklist
            </p>
          </div>
        </div>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            {/* Audit Details */}
            <Card>
              <CardHeader>
                <CardTitle>Audit Details</CardTitle>
                <CardDescription>Basic information about this audit</CardDescription>
              </CardHeader>
              <CardContent className="space-y-4">
                <FormField
                  control={form.control}
                  name="title"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Audit Title *</FormLabel>
                      <FormControl>
                        <Input placeholder="e.g., Q1 2026 Document Control Audit" {...field} />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <div className="grid gap-4 sm:grid-cols-2">
                  <FormField
                    control={form.control}
                    name="iso_clause"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>ISO Clause</FormLabel>
                        <FormControl>
                          <Input placeholder="e.g., 7.5.3" {...field} />
                        </FormControl>
                        <FormMessage />
                      </FormItem>
                    )}
                  />

                  <FormField
                    control={form.control}
                    name="audit_date"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Audit Date *</FormLabel>
                        <Popover>
                          <PopoverTrigger asChild>
                            <FormControl>
                              <Button
                                variant="outline"
                                className={cn(
                                  'w-full justify-start text-left font-normal',
                                  !field.value && 'text-muted-foreground'
                                )}
                              >
                                <Calendar className="mr-2 h-4 w-4" />
                                {field.value ? format(field.value, 'PPP') : 'Select date'}
                              </Button>
                            </FormControl>
                          </PopoverTrigger>
                          <PopoverContent className="w-auto p-0" align="start">
                            <CalendarComponent
                              mode="single"
                              selected={field.value}
                              onSelect={field.onChange}
                              initialFocus
                            />
                          </PopoverContent>
                        </Popover>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>

                <FormField
                  control={form.control}
                  name="department_id"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Department</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Select department (optional)" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {departments.map((dept) => (
                            <SelectItem key={dept.id} value={dept.id}>
                              {dept.name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <FormField
                  control={form.control}
                  name="description"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Description</FormLabel>
                      <FormControl>
                        <Textarea
                          placeholder="Describe the scope and objectives of this audit..."
                          {...field}
                        />
                      </FormControl>
                      <FormMessage />
                    </FormItem>
                  )}
                />
              </CardContent>
            </Card>

            {/* Checklist Items */}
            <Card>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div>
                    <CardTitle>Checklist Items</CardTitle>
                    <CardDescription>Define the requirements to check</CardDescription>
                  </div>
                  <Button
                    type="button"
                    variant="outline"
                    size="sm"
                    onClick={() => append({ requirement: '', evidence_required: '' })}
                  >
                    <Plus className="h-4 w-4 mr-2" />
                    Add Item
                  </Button>
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                {fields.map((field, index) => (
                  <div key={field.id} className="space-y-3 p-4 border rounded-lg">
                    <div className="flex items-center justify-between">
                      <span className="font-medium text-sm">Item {index + 1}</span>
                      {fields.length > 1 && (
                        <Button
                          type="button"
                          variant="ghost"
                          size="icon"
                          onClick={() => remove(index)}
                        >
                          <Trash2 className="h-4 w-4 text-destructive" />
                        </Button>
                      )}
                    </div>
                    <FormField
                      control={form.control}
                      name={`items.${index}.requirement`}
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Requirement *</FormLabel>
                          <FormControl>
                            <Textarea
                              placeholder="What requirement will be checked?"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                    <FormField
                      control={form.control}
                      name={`items.${index}.evidence_required`}
                      render={({ field }) => (
                        <FormItem>
                          <FormLabel>Evidence Required</FormLabel>
                          <FormControl>
                            <Input
                              placeholder="What evidence should be reviewed?"
                              {...field}
                            />
                          </FormControl>
                          <FormMessage />
                        </FormItem>
                      )}
                    />
                  </div>
                ))}
              </CardContent>
            </Card>

            {/* Submit */}
            <div className="flex justify-end gap-3">
              <Button type="button" variant="outline" onClick={() => navigate('/audits')}>
                Cancel
              </Button>
              <Button type="submit" disabled={isSubmitting}>
                <Save className="h-4 w-4 mr-2" />
                {isSubmitting ? 'Creating...' : 'Create Audit'}
              </Button>
            </div>
          </form>
        </Form>
      </div>
    </AppLayout>
  );
}
