import React, { createContext, useContext, useState, useCallback, useEffect, ReactNode } from 'react';
import type { Json } from '@/integrations/supabase/types';
import { useLocation } from 'react-router-dom';
import { supabase } from '@/integrations/supabase/client';
import { useAuth } from '@/hooks/useAuth';
import { useTenant } from '@/hooks/useTenant';
import { toast } from '@/hooks/use-toast';
import type { 
  EdithContextValue, 
  EdithState, 
  EdithMessage, 
  EdithConversation, 
  EdithContext as EdithCtx 
} from '@/types/edith';

const EdithContext = createContext<EdithContextValue | undefined>(undefined);

const initialState: EdithState = {
  isOpen: false,
  isLoading: false,
  conversations: [],
  currentConversation: null,
  error: null,
};

export function EdithProvider({ children }: { children: ReactNode }) {
  const [state, setState] = useState<EdithState>(initialState);
  const { user, profile } = useAuth();
  const { tenant } = useTenant();
  const location = useLocation();

  // Create new conversation
  const createConversation = useCallback(async (): Promise<EdithConversation | null> => {
    if (!user || !profile?.tenant_id) return null;

    try {
      // conversation_number is auto-generated by database trigger
      const insertData = {
        user_id: user.id,
        tenant_id: profile.tenant_id,
        context: { currentPage: location.pathname } as unknown as Json,
        conversation_number: '', // Will be overwritten by trigger
      };
      
      const { data, error } = await supabase
        .from('edith_conversations')
        .insert([insertData])
        .select('*')
        .single();

      if (error) throw error;

      const newConversation: EdithConversation = {
        id: data.id,
        conversationNumber: data.conversation_number,
        title: data.title,
        messages: [],
        context: data.context as EdithCtx || {},
        createdAt: new Date(data.created_at),
        updatedAt: new Date(data.updated_at),
      };

      return newConversation;
    } catch (error) {
      console.error('Failed to create conversation:', error);
      return null;
    }
  }, [user, profile?.tenant_id, location.pathname]);

  // Start new conversation
  const startNewConversation = useCallback(async () => {
    const newConversation = await createConversation();
    if (newConversation) {
      setState(prev => ({
        ...prev,
        currentConversation: newConversation,
        conversations: [newConversation, ...prev.conversations],
      }));
    }
  }, [createConversation]);

  // Open Edith
  const openEdith = useCallback(() => {
    setState(prev => ({ ...prev, isOpen: true }));
    if (!state.currentConversation) {
      startNewConversation();
    }
  }, [state.currentConversation, startNewConversation]);

  // Close Edith
  const closeEdith = useCallback(() => {
    setState(prev => ({ ...prev, isOpen: false }));
  }, []);

  // Toggle Edith
  const toggleEdith = useCallback(() => {
    if (state.isOpen) {
      closeEdith();
    } else {
      openEdith();
    }
  }, [state.isOpen, closeEdith, openEdith]);

  // Send message
  const sendMessage = useCallback(async (messageContent: string) => {
    if (!messageContent.trim() || state.isLoading) return;
    if (!user) {
      toast({
        title: 'Authentication required',
        description: 'Please log in to use Edith',
        variant: 'destructive',
      });
      return;
    }

    // Ensure we have a conversation
    let conversation = state.currentConversation;
    if (!conversation) {
      conversation = await createConversation();
      if (!conversation) {
        toast({
          title: 'Error',
          description: 'Failed to start conversation',
          variant: 'destructive',
        });
        return;
      }
      setState(prev => ({
        ...prev,
        currentConversation: conversation,
        conversations: [conversation!, ...prev.conversations],
      }));
    }

    // Add user message
    const userMessage: EdithMessage = {
      id: crypto.randomUUID(),
      role: 'user',
      content: messageContent,
      createdAt: new Date(),
    };

    setState(prev => ({
      ...prev,
      isLoading: true,
      error: null,
      currentConversation: prev.currentConversation
        ? {
            ...prev.currentConversation,
            messages: [...prev.currentConversation.messages, userMessage],
          }
        : null,
    }));

    try {
      // Save user message to database
      await supabase.from('edith_messages').insert({
        conversation_id: conversation.id,
        tenant_id: profile?.tenant_id,
        role: 'user',
        content: messageContent,
      });

      // Get session token
      const { data: sessionData } = await supabase.auth.getSession();
      const token = sessionData?.session?.access_token;

      // Prepare messages for API
      const apiMessages = [
        ...state.currentConversation?.messages.map(m => ({
          role: m.role,
          content: m.content,
        })) || [],
        { role: 'user' as const, content: messageContent },
      ];

      // Call Edith API
      const response = await fetch(
        `${import.meta.env.VITE_SUPABASE_URL}/functions/v1/edith-chat`,
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            Authorization: `Bearer ${token}`,
          },
          body: JSON.stringify({
            messages: apiMessages,
            conversationId: conversation.id,
          }),
        }
      );

      if (!response.ok) {
        const errorData = await response.json();
        throw new Error(errorData.error || `Request failed: ${response.status}`);
      }

      const data = await response.json();

      // Add assistant message
      const assistantMessage: EdithMessage = {
        id: crypto.randomUUID(),
        role: 'assistant',
        content: data.message,
        toolCalls: data.tool_calls,
        createdAt: new Date(),
      };

      // Save assistant message to database
      await supabase.from('edith_messages').insert({
        conversation_id: conversation.id,
        tenant_id: profile?.tenant_id,
        role: 'assistant',
        content: data.message,
        tool_calls: data.tool_calls,
      });

      setState(prev => ({
        ...prev,
        isLoading: false,
        currentConversation: prev.currentConversation
          ? {
              ...prev.currentConversation,
              messages: [...prev.currentConversation.messages, assistantMessage],
            }
          : null,
      }));

    } catch (error) {
      console.error('Edith chat error:', error);
      const errorMessage = error instanceof Error ? error.message : 'Failed to get response';
      
      setState(prev => ({
        ...prev,
        isLoading: false,
        error: errorMessage,
      }));

      toast({
        title: 'Edith Error',
        description: errorMessage,
        variant: 'destructive',
      });
    }
  }, [state.isLoading, state.currentConversation, user, profile?.tenant_id, createConversation]);

  // Select conversation (from memory)
  const selectConversation = useCallback((id: string) => {
    const conversation = state.conversations.find(c => c.id === id);
    if (conversation) {
      setState(prev => ({ ...prev, currentConversation: conversation }));
    }
  }, [state.conversations]);

  // Load conversation from database
  const loadConversation = useCallback(async (id: string) => {
    if (!user) return;

    try {
      // Get conversation
      const { data: convData, error: convError } = await supabase
        .from('edith_conversations')
        .select('*')
        .eq('id', id)
        .single();

      if (convError) throw convError;

      // Get messages
      const { data: messagesData, error: msgError } = await supabase
        .from('edith_messages')
        .select('*')
        .eq('conversation_id', id)
        .order('created_at', { ascending: true });

      if (msgError) throw msgError;

      const loadedConversation: EdithConversation = {
        id: convData.id,
        conversationNumber: convData.conversation_number,
        title: convData.title,
        messages: (messagesData || []).map(m => ({
          id: m.id,
          role: m.role as 'user' | 'assistant',
          content: m.content,
          toolCalls: m.tool_calls as any,
          createdAt: new Date(m.created_at),
        })),
        context: convData.context as EdithCtx || {},
        createdAt: new Date(convData.created_at),
        updatedAt: new Date(convData.updated_at),
      };

      setState(prev => ({
        ...prev,
        currentConversation: loadedConversation,
        conversations: prev.conversations.some(c => c.id === id)
          ? prev.conversations.map(c => c.id === id ? loadedConversation : c)
          : [loadedConversation, ...prev.conversations],
      }));
    } catch (error) {
      console.error('Failed to load conversation:', error);
      toast({
        title: 'Error',
        description: 'Failed to load conversation',
        variant: 'destructive',
      });
    }
  }, [user]);

  // Clear error
  const clearError = useCallback(() => {
    setState(prev => ({ ...prev, error: null }));
  }, []);

  // Update context
  const updateContext = useCallback((context: Partial<EdithCtx>) => {
    setState(prev => ({
      ...prev,
      currentConversation: prev.currentConversation
        ? {
            ...prev.currentConversation,
            context: { ...prev.currentConversation.context, ...context },
          }
        : null,
    }));
  }, []);

  // Update context when location changes
  useEffect(() => {
    updateContext({ currentPage: location.pathname });
  }, [location.pathname, updateContext]);

  // Keyboard shortcut
  useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if ((e.metaKey || e.ctrlKey) && e.key === 'k') {
        e.preventDefault();
        toggleEdith();
      }
      if (e.key === 'Escape' && state.isOpen) {
        closeEdith();
      }
    };

    document.addEventListener('keydown', handleKeyDown);
    return () => document.removeEventListener('keydown', handleKeyDown);
  }, [toggleEdith, closeEdith, state.isOpen]);

  const value: EdithContextValue = {
    ...state,
    openEdith,
    closeEdith,
    toggleEdith,
    sendMessage,
    startNewConversation,
    selectConversation,
    loadConversation,
    clearError,
    updateContext,
  };

  return (
    <EdithContext.Provider value={value}>
      {children}
    </EdithContext.Provider>
  );
}

export function useEdith() {
  const context = useContext(EdithContext);
  if (context === undefined) {
    throw new Error('useEdith must be used within an EdithProvider');
  }
  return context;
}
