import { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { useForm } from 'react-hook-form';
import { zodResolver } from '@hookform/resolvers/zod';
import { z } from 'zod';
import { format } from 'date-fns';
import {
  GraduationCap,
  ArrowLeft,
  Save,
  Calendar,
  Star,
} from 'lucide-react';
import { AppLayout } from '@/components/layout/AppLayout';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import {
  Form,
  FormControl,
  FormField,
  FormItem,
  FormLabel,
  FormMessage,
  FormDescription,
} from '@/components/ui/form';
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select';
import { Calendar as CalendarComponent } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import { RadioGroup, RadioGroupItem } from '@/components/ui/radio-group';
import { Label } from '@/components/ui/label';
import { useToast } from '@/hooks/use-toast';
import { useAuth } from '@/hooks/useAuth';
import { supabase } from '@/integrations/supabase/client';
import { cn } from '@/lib/utils';

interface Profile {
  id: string;
  full_name: string;
}

const SCORE_CATEGORIES = [
  { key: 'score_knowledge_expertise', label: 'Knowledge & Expertise' },
  { key: 'score_presentation_skills', label: 'Presentation Skills' },
  { key: 'score_learner_engagement', label: 'Learner Engagement' },
  { key: 'score_time_management', label: 'Time Management' },
  { key: 'score_material_preparation', label: 'Material Preparation' },
  { key: 'score_assessment_quality', label: 'Assessment Quality' },
  { key: 'score_professionalism', label: 'Professionalism' },
  { key: 'score_continuous_improvement', label: 'Continuous Improvement' },
];

const formSchema = z.object({
  facilitator_id: z.string().min(1, 'Select a facilitator'),
  evaluation_period_start: z.date({ required_error: 'Start date is required' }),
  evaluation_period_end: z.date({ required_error: 'End date is required' }),
  score_knowledge_expertise: z.string().min(1, 'Required'),
  score_presentation_skills: z.string().min(1, 'Required'),
  score_learner_engagement: z.string().min(1, 'Required'),
  score_time_management: z.string().min(1, 'Required'),
  score_material_preparation: z.string().min(1, 'Required'),
  score_assessment_quality: z.string().min(1, 'Required'),
  score_professionalism: z.string().min(1, 'Required'),
  score_continuous_improvement: z.string().min(1, 'Required'),
  strengths: z.string().optional(),
  areas_for_improvement: z.string().optional(),
  development_plan: z.string().optional(),
  evaluator_comments: z.string().optional(),
});

type FormData = z.infer<typeof formSchema>;

export default function FacilitatorEvaluationCreate() {
  const navigate = useNavigate();
  const { toast } = useToast();
  const { profile } = useAuth();
  const [facilitators, setFacilitators] = useState<Profile[]>([]);
  const [isSubmitting, setIsSubmitting] = useState(false);

  const form = useForm<FormData>({
    resolver: zodResolver(formSchema),
    defaultValues: {
      strengths: '',
      areas_for_improvement: '',
      development_plan: '',
      evaluator_comments: '',
    },
  });

  useEffect(() => {
    async function fetchFacilitators() {
      const { data } = await supabase
        .from('profiles')
        .select('id, full_name')
        .eq('is_active', true)
        .order('full_name');
      if (data) setFacilitators(data);
    }
    fetchFacilitators();
  }, []);

  async function onSubmit(data: FormData) {
    if (!profile) return;
    setIsSubmitting(true);

    try {
      const scores = {
        score_knowledge_expertise: parseInt(data.score_knowledge_expertise),
        score_presentation_skills: parseInt(data.score_presentation_skills),
        score_learner_engagement: parseInt(data.score_learner_engagement),
        score_time_management: parseInt(data.score_time_management),
        score_material_preparation: parseInt(data.score_material_preparation),
        score_assessment_quality: parseInt(data.score_assessment_quality),
        score_professionalism: parseInt(data.score_professionalism),
        score_continuous_improvement: parseInt(data.score_continuous_improvement),
      };

      const overall_score =
        Object.values(scores).reduce((sum, s) => sum + s, 0) / Object.values(scores).length;

      const { data: evaluation, error } = await supabase
        .from('facilitator_annual_evaluations')
        .insert({
          evaluation_number: '', // Will be auto-generated by trigger
          facilitator_id: data.facilitator_id,
          evaluator_id: profile.id,
          evaluation_period_start: format(data.evaluation_period_start, 'yyyy-MM-dd'),
          evaluation_period_end: format(data.evaluation_period_end, 'yyyy-MM-dd'),
          ...scores,
          overall_score,
          strengths: data.strengths || null,
          areas_for_improvement: data.areas_for_improvement || null,
          development_plan: data.development_plan || null,
          evaluator_comments: data.evaluator_comments || null,
          tenant_id: profile.tenant_id,
          status: 'draft',
        } as any)
        .select()
        .single();

      if (error) throw error;

      toast({
        title: 'Evaluation Created',
        description: `Evaluation ${evaluation.evaluation_number} has been created.`,
      });

      navigate(`/facilitator-evaluations/${evaluation.id}`);
    } catch (error: any) {
      toast({
        variant: 'destructive',
        title: 'Error',
        description: error.message,
      });
    } finally {
      setIsSubmitting(false);
    }
  }

  function ScoreSelector({ name, label }: { name: keyof FormData; label: string }) {
    return (
      <FormField
        control={form.control}
        name={name}
        render={({ field }) => (
          <FormItem className="space-y-2">
            <FormLabel>{label}</FormLabel>
            <FormControl>
              <RadioGroup
                onValueChange={field.onChange}
                value={field.value as string}
                className="flex gap-2"
              >
                {[1, 2, 3, 4, 5].map((score) => (
                  <div key={score} className="flex flex-col items-center">
                    <RadioGroupItem
                      value={score.toString()}
                      id={`${name}-${score}`}
                      className="sr-only peer"
                    />
                    <Label
                      htmlFor={`${name}-${score}`}
                      className={cn(
                        'w-10 h-10 rounded-full border-2 flex items-center justify-center cursor-pointer transition-colors',
                        field.value === score.toString()
                          ? 'border-primary bg-primary text-primary-foreground'
                          : 'border-muted-foreground/30 hover:border-primary/50'
                      )}
                    >
                      {score}
                    </Label>
                  </div>
                ))}
              </RadioGroup>
            </FormControl>
            <FormMessage />
          </FormItem>
        )}
      />
    );
  }

  return (
    <AppLayout>
      <div className="max-w-3xl mx-auto space-y-6">
        <div className="flex items-center gap-4">
          <Button variant="ghost" size="icon" onClick={() => navigate('/facilitator-evaluations')}>
            <ArrowLeft className="h-5 w-5" />
          </Button>
          <div>
            <h1 className="text-2xl font-bold tracking-tight flex items-center gap-2">
              <GraduationCap className="h-6 w-6 text-primary" />
              New Facilitator Evaluation
            </h1>
            <p className="text-muted-foreground">
              Annual performance evaluation form
            </p>
          </div>
        </div>

        <Form {...form}>
          <form onSubmit={form.handleSubmit(onSubmit)} className="space-y-6">
            {/* Basic Info */}
            <Card>
              <CardHeader>
                <CardTitle>Evaluation Details</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <FormField
                  control={form.control}
                  name="facilitator_id"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Facilitator *</FormLabel>
                      <Select onValueChange={field.onChange} value={field.value}>
                        <FormControl>
                          <SelectTrigger>
                            <SelectValue placeholder="Select facilitator" />
                          </SelectTrigger>
                        </FormControl>
                        <SelectContent>
                          {facilitators.map((f) => (
                            <SelectItem key={f.id} value={f.id}>
                              {f.full_name}
                            </SelectItem>
                          ))}
                        </SelectContent>
                      </Select>
                      <FormMessage />
                    </FormItem>
                  )}
                />

                <div className="grid gap-4 sm:grid-cols-2">
                  <FormField
                    control={form.control}
                    name="evaluation_period_start"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Period Start *</FormLabel>
                        <Popover>
                          <PopoverTrigger asChild>
                            <FormControl>
                              <Button
                                variant="outline"
                                className={cn(
                                  'w-full justify-start text-left font-normal',
                                  !field.value && 'text-muted-foreground'
                                )}
                              >
                                <Calendar className="mr-2 h-4 w-4" />
                                {field.value ? format(field.value, 'PPP') : 'Select date'}
                              </Button>
                            </FormControl>
                          </PopoverTrigger>
                          <PopoverContent className="w-auto p-0">
                            <CalendarComponent
                              mode="single"
                              selected={field.value}
                              onSelect={field.onChange}
                              initialFocus
                            />
                          </PopoverContent>
                        </Popover>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                  <FormField
                    control={form.control}
                    name="evaluation_period_end"
                    render={({ field }) => (
                      <FormItem>
                        <FormLabel>Period End *</FormLabel>
                        <Popover>
                          <PopoverTrigger asChild>
                            <FormControl>
                              <Button
                                variant="outline"
                                className={cn(
                                  'w-full justify-start text-left font-normal',
                                  !field.value && 'text-muted-foreground'
                                )}
                              >
                                <Calendar className="mr-2 h-4 w-4" />
                                {field.value ? format(field.value, 'PPP') : 'Select date'}
                              </Button>
                            </FormControl>
                          </PopoverTrigger>
                          <PopoverContent className="w-auto p-0">
                            <CalendarComponent
                              mode="single"
                              selected={field.value}
                              onSelect={field.onChange}
                              initialFocus
                            />
                          </PopoverContent>
                        </Popover>
                        <FormMessage />
                      </FormItem>
                    )}
                  />
                </div>
              </CardContent>
            </Card>

            {/* Scoring */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Star className="h-5 w-5 text-foreground/60" />
                  Performance Scores
                </CardTitle>
                <CardDescription>Rate each category from 1 (Poor) to 5 (Excellent)</CardDescription>
              </CardHeader>
              <CardContent className="grid gap-6 sm:grid-cols-2">
                {SCORE_CATEGORIES.map((cat) => (
                  <ScoreSelector key={cat.key} name={cat.key as keyof FormData} label={cat.label} />
                ))}
              </CardContent>
            </Card>

            {/* Comments */}
            <Card>
              <CardHeader>
                <CardTitle>Feedback & Development</CardTitle>
              </CardHeader>
              <CardContent className="space-y-4">
                <FormField
                  control={form.control}
                  name="strengths"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Strengths</FormLabel>
                      <FormControl>
                        <Textarea
                          placeholder="Key strengths observed during the evaluation period..."
                          {...field}
                        />
                      </FormControl>
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="areas_for_improvement"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Areas for Improvement</FormLabel>
                      <FormControl>
                        <Textarea
                          placeholder="Areas that need development..."
                          {...field}
                        />
                      </FormControl>
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="development_plan"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Development Plan</FormLabel>
                      <FormControl>
                        <Textarea
                          placeholder="Recommended development activities..."
                          {...field}
                        />
                      </FormControl>
                    </FormItem>
                  )}
                />
                <FormField
                  control={form.control}
                  name="evaluator_comments"
                  render={({ field }) => (
                    <FormItem>
                      <FormLabel>Additional Comments</FormLabel>
                      <FormControl>
                        <Textarea
                          placeholder="Any additional observations or comments..."
                          {...field}
                        />
                      </FormControl>
                    </FormItem>
                  )}
                />
              </CardContent>
            </Card>

            {/* Submit */}
            <div className="flex justify-end gap-3">
              <Button type="button" variant="outline" onClick={() => navigate('/facilitator-evaluations')}>
                Cancel
              </Button>
              <Button type="submit" disabled={isSubmitting}>
                <Save className="h-4 w-4 mr-2" />
                {isSubmitting ? 'Saving...' : 'Save Evaluation'}
              </Button>
            </div>
          </form>
        </Form>
      </div>
    </AppLayout>
  );
}
